---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: limit-test
  name: limit-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: limit-test
  template:
    metadata:
      labels:
        run: limit-test
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - while true; do sleep 2; done
        image: busybox
        imagePullPolicy: Always
        name: limit-test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: hotrod
    app.kubernetes.io/instance: jaeger
  name: jaeger-hotrod
  namespace: hotrod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: hotrod
      app.kubernetes.io/instance: jaeger
      app.kubernetes.io/name: jaeger
  template:
    metadata:
      labels:
        app.kubernetes.io/component: hotrod
        app.kubernetes.io/instance: jaeger
        app.kubernetes.io/name: jaeger
    spec:
      containers:
      - env:
        - name: JAEGER_AGENT_HOST
          value: jaeger-agent.jaeger.svc.cluster.local
        - name: JAEGER_AGENT_PORT
          value: "6831"
        image: jaegertracing/example-hotrod:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        name: jaeger-hotrod
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080

---
apiVersion: v1
kind: Namespace
metadata:
  name: hotrod
  labels:
    istio-injection: enabled

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: hotrod
    app.kubernetes.io/instance: jaeger
  name: jaeger-hotrod
  namespace: hotrod
spec:
  ports:
  - name: hotrod
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: hotrod
    app.kubernetes.io/instance: jaeger
  type: ClusterIP

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: hotrod
  name: hotrod-service
spec:
  hosts:
    - "*"
  gateways:
    - bookinfo/bookinfo-gateway
  http:
    - match:
        - uri:
            exact: /hotrod
      route:
        - destination:
            host: jaeger-hotrod.hotrod.svc.cluster.local
            port:
              number: 80

